[package]
name = "last_stage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-trait = "0.1.53"
hashring = "0.3.0"
tokio = { version = "1.17.0", features = ["sync", "macros", "rt-multi-thread", "time"]}